<?php
$campoLingua = 'Language';
$campoLinguaDescr = 'What language do you prefer?';
$campoAdSenseIdDescr = 'Your Adsense ID (pub-....) <b>Enter Numbers Only</b>! (<a href="http://adsensexplosion.wordpress.com/2013/09/25/google-adsense-id-where-do-i-get-it/" target="_blank">Further Details</a>)';
$campoAdSenseChannelDescr = '(Optional) <b>Enter Numbers Only</b> ! (<a href="http://www.google.com/adsense/support/bin/answer.py?answer=9868" target="_blank">Further Details</a>)';
$campoProblema3Annuncio = 'Overrule 3 Ads count';
$campoProblema3AnnuncioDescr = 'In some Themes (like Mystique) Adsense Plugin Explosion is not able to show 3 Ads. In such cases just overrule by clicking this box. If you have no problems (in most themes) let it unchecked !';
$campoEscludiCSS = 'use external CSS';
$campoEscludiCSSDescr = 'switch the styling of the ads to use CSS styles defined in a stylesheet rather than inline styles. If you have no problems (in most themes) let it unchecked !';
$campoDisattivaSuMobile = 'disabled for Mobile Themes';
$campoDisattivaSuMobileDescr = 'plugin is disabled when using mobile themes. If you have no problems (in most themes) let it unchecked !';
$campoAsync = 'asynchronous ad (Beta)';
$campoAsyncDescr = 'It offers a better user experience for your site\'s visitors.';
$impostazioniGenerali = 'General Settings';
$cheTipoDiUtenteSei = 'What kind of user are you ?';
$utenteBase = '> <b>Basic User</b>. You just want to add Google Ads with minimum effort.';
$utenteEsperto = '> <b>Experienced User</b>. You want to optimize to get the most out of your ads and don\'t mind doing some option-setting and tuning work.';
$configuraTuoiAnnunci = 'Adjust your Ads';
$puoiImpostareFino8DiversiTipiDiAnnuncio = 'You can set up to 8 different visual Types of Ads.';
$TestoImmagini = '>Text &amp; Image ads';
$soloTesto = '>Text only';
$soloImmagini = '>Images only';
$blocchiDiLink = '>Blocklink';
$quadrati = '>Square';
$arrotondati = '>Round';
$moltoArrotondati = '>very Round';
$soloSeDiversoDaImpostazioniGenerali = 'only if different from<br>general settings';
$istruzioniDataAdSlot = 'ID of the ad. You can find it also into javascript ad code. (numbers only)';
$mostraAnnuncioNr = 'Show Ad Nr';
$quandoLaLarghezza = 'when width <';
$nonUsare = '>Don\'t use';
$usaQuestaFunzioneSuTemiResponsive = 'You can use this feature (BETA) on responsive themes';
$cliccaQuiPerVedereEsempiBanner = 'Click <a href="https://support.google.com/adsense/bin/answer.py?hl=en&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=185665" target="_blank">here</a> to see examples of the different sizes.';
$angoli = 'Corners: ';
$margineAttornoAnnuncio = 'Margin around Ad:';
$doveMostrareGliAnnunci = 'Where to show Ads';
$doveMostrareGliAnnunciDescr = 'Now do your settings where ads should be displayed within content area. For insertion into other Blog Parts you can use Widget.';
$postSingoliPagStatiche = 'Single Posts &amp; Static Pages';
$postSingoliPagStaticheDescr = 'On single Pages where ONE Post is displayed in full length or on static pages.';
$checkAdsenseopt = '> Only use in articles which contain &lt;!--adsenseopt--&gt;: <span class="ao_explain"> To use the Plugin only in distinct articles mark that box.<br>If you want to use the Plugin to ad Ads generally uncheck this !</span>';
$checkOmitPag = '> Do not show Ads on static pages.<span class="ao_explain"> If you don\'t want Ads on a special page you can use the &lt;!--noads--&gt; tag !<br>Checking this box will omit Ads for <b>all</b> static pages !!!</span>';

$checkPolicyProtect = '> Hide banner ads on pages that could violate Google policy.<span class="ao_explain"> <a href="https://support.google.com/adsense/bin/answer.py?hl=en&stc=aspe-1pp-it&answer=48182" target = "_blank">For more information read the terms.</a></span>';
$nellePagineMostranoMoltiArticoli = 'On pages showing more posts. (archives, normal Homepage etc.)';
$nonMostrareAdSuQuestePag = 'Don\'t show Ads on these pages:';
$supportaIlPlugin = 'Support for plugin';
$dono = 'Gift a few clicks to the development of this great plugin. My earnings remain virtually unchanged and I can use all the features.<span class="ao_explain"><br>If you are more miser of Scrooge McDuck, deselect it.</span>';
$puoInserireAnnunciUsandoWidget = 'You can also insert Google Ads by using the widget.';
$numeroDiLinks = 'Number of Links:';
$mostraSoloSeArticoloPiuLungoDi = 'Only show if article is longer than:';
$caratteri = 'characters.';
$caratteriDescr = '3000 chars = medium / around 5000 chars = long Posts';
$postMultipli = 'Multiple Posts';
$intestazioniColonnePostMultipli = '<th>Ad Nr.</th><th>Ad Type</th><th>Show With</th><th>Aligment</th>';
$alto = '>Top';
$mezzo = '>Middle';
$basso = '>Bottom';
$caso = '>Random';
$centro = '>Center';
$sinistra = '>Left';
$destra = '>Right';
$nascondi = '>Don\'t show';
$centraleSopraTitolo = '>center above Title';
$sinistraSopraTitolo = '>left above Title';
$destraSopraTitolo = '>right above Title';
$centraleSottoTitolo = '>center below Title';
$sinistraSottoTitolo = '>left below Title';
$destraSottoTitolo = '>right below Title';
$aggiornaLeOpzioni = 'Update options';
$titoloPrivacy = 'AdSense program policies';
$spiegazioneBanPrivacy = 'You can not display ads on pages with violent content, copyright infringement, an invitation to fraudulent clicks, etc..
Those who violate the rules, are expelled from the program forever.';
$spiegazioneUtilizzoPrivacy = 'AdSense publishers must have and abide by a privacy policy that discloses that third parties may be placing and reading cookies on your users\' browsers to collect information as a result of ad serving on your website.
<a target="_blank" href= "https://support.google.com/adsense/bin/answer.py?hl=en&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=48182#cook">
(See the Cookie section)
</a>
<p> To include the Privacy Policy on your site add &lt;!-- adsenseprivacypolicy --&gt; to the page or post where you want the privacy policy to appear.</p>';
$informativaSullaPrivacy = 'Statement of Privacy';
$dettagli = 'Details';

$sizes = array();
$sizes[] = array('desc' => '300 x 250 Medium rectangle', 'text' => '300x250');
$sizes[] = array('desc' => '336 x 280 Large rectangle', 'text' => '336x280');
$sizes[] = array('desc' => '728 x 90 Leaderboard', 'text' => '728x90');
$sizes[] = array('desc' => '160 x 600 Wide skyscraper', 'text' => '160x600');
$sizes[] = array('desc' => '320 x 50 Mobile banner', 'text' => '320x50');
$sizes[] = array('desc' => '234 x 60 Half banner', 'text' => '234x60');
$sizes[] = array('desc' => '320 x 100 Great banner for mobile devices', 'text' => '320x100');
$sizes[] = array('desc' => '468 x 60 Banner', 'text' => '468x60');
$sizes[] = array('desc' => '970 x 90 Leaderboard great', 'text' => '970x90');
$sizes[] = array('desc' => '970 x 250 Billboard', 'text' => '970x250');
$sizes[] = array('desc' => '120 x 600 Skyscraper', 'text' => '120x600');
$sizes[] = array('desc' => '120 x 240 Vertical banner', 'text' => '120x240');
$sizes[] = array('desc' => '300 x 600 Big skyscraper', 'text' => '300x600');
$sizes[] = array('desc' => '300 x 1050 Vertical', 'text' => '300x1050');
$sizes[] = array('desc' => '250 x 250 Square', 'text' => '250x250');
$sizes[] = array('desc' => '200 x 200 Small square', 'text' => '200x200');
$sizes[] = array('desc' => '180 x 150 Small rectangle', 'text' => '180x150');
$sizes[] = array('desc' => '125 x 125 Button', 'text' => '125x125');
$sizes[] = array('desc' => 'Dynamic Responsive', 'text' => 'dynamic');
$sizes[] = array('desc' => 'Responsive', 'text' => 'responsive');
?>