<?php
$campoLingua = 'Lenguaje';
$campoLinguaDescr = '&#191;Cual es tu idioma preferido?';
$campoAdSenseIdDescr = 'Tu ID de Adsense (pub-....) <b>Introducir solo numeros</b>!  (<a href="http://adsensexplosion.wordpress.com/2013/09/25/google-adsense-id-where-do-i-get-it/" target="_blank">Mas Detalles</a>)';
$campoAdSenseChannelDescr = '(Opcional) <b>Introducir solo numeros</b> ! (<a href="http://www.google.com/adsense/support/bin/answer.py?answer=9868" target="_blank">Mas Detalles</a>)';
$campoProblema3Annuncio = 'Overrule 3 Ads count';
$campoProblema3AnnuncioDescr = 'En algunos Themes (como Mystique) Adsense Plugin Explosion no es capaz de mostrar tres anuncios. En estos casos, s&#243;lo anular, haga clic en esta casilla. Si usted no tiene problemas (en la mayor&#237;a de los temas) dejar sin marcar!';
$campoEscludiCSS = 'usa una CSS externa';
$campoEscludiCSSDescr = 'cambiar el estilo de los anuncios, el uso de estilos CSS definida en una hoja de estilo en lugar de estilos internos. Si usted no tiene problemas (en la mayor&#237;a de los temas) dejar sin marcar!';
$campoDisattivaSuMobile = 'descuento en los tel&#233;fonos m&#243;viles';
$campoDisattivaSuMobileDescr = 'plugin est&#225; desactivado, cuando el uso de temas m&#243;viles. Si usted no tiene problemas (en la mayor&#237;a de los temas) dejar sin marcar!';
$campoAsync = 'utilizar anuncios as&#237;ncrono (Beta)';
$campoAsyncDescr = 'ofrece una mejor experiencia de usuario a los visitantes del sitio.';
$impostazioniGenerali = 'Configuraci&#243;n general';
$cheTipoDiUtenteSei = '&#191;Qu&#233; tipo de usuario es usted ?';
$utenteBase = '> <b>Usu&#225;rio Basico</b>. Usted s&#243;lo desea agregar GoogleAds con el m&#237;nimo esfuerzo.';
$utenteEsperto = '> <b>Usuario con Experiencia</b>. Usted desea optimizar el trabajo para obtener el m&#225;ximo rendimiento posible.';
$configuraTuoiAnnunci = 'Ajuste sus Ads';
$puoiImpostareFino8DiversiTipiDiAnnuncio = 'Usted puede configurar 8 tipos distintos de Ads';
$TestoImmagini = '>Texto &amp; Imagen ads';
$soloTesto = '>Solo texto';
$soloImmagini = '>Solo imagenes';
$blocchiDiLink = '>Bloquear enlace';
$quadrati = '>Cuadrado';
$arrotondati = '>Redondo';
$moltoArrotondati = '>Muy redondo';
$soloSeDiversoDaImpostazioniGenerali = 'S&#243;lo si es diferente de<br>las configuraciones generales';
$istruzioniDataAdSlot = 'ID del anuncio. Tambi&egrave;n se encuentra en el c&#243;digo javascript del anuncio. (s&#243;lo n&ugrave;meros)';
$mostraAnnuncioNr = 'Mostrar Ad Nr';
$quandoLaLarghezza = 'cuando el ancho <';
$nonUsare = '>No usar';
$usaQuestaFunzioneSuTemiResponsive = 'Puede usar esta funci&#243;n (BETA) en temas responsive';
$cliccaQuiPerVedereEsempiBanner = 'Haga clic <a href="https://support.google.com/adsense/bin/answer.py?hl=es&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=185665" target="_blank">aqu&igrave;</a> para ver ejemplos de distintos tama&#241;os.';
$angoli = 'Esquinas: ';
$margineAttornoAnnuncio = 'Margen alrededor del Ads:';
$doveMostrareGliAnnunci = 'D&#243;nde mostrar Ads';
$doveMostrareGliAnnunciDescr = 'Ahora sus configuraciones sobre los Ads deber&#237;an ser mostradas sin contenido. Para insertar en blogs u otros websites use Widgets.';
$postSingoliPagStatiche = 'Solo Posts &amp; P&#225;ginas est&#225;ticas';
$postSingoliPagStaticheDescr = 'En p&#225;ginas simples donde un post es mostrado &#237;ntegro, o en p&#225;ginas est&#225;ticas.';
$checkAdsenseopt = '> Solo use esto en art&#237;culos que contengan &lt;!--adsenseopt--&gt;: <span class="ao_explain"> Para usar el Plugin solamente en art&#237;culos distintos marque esto.<br>Si va a usar este Plugin para agregar Ads en general desmarque esto!</span>';
$checkOmitPag = '> No mostrar Ads en p&#225;ginas est&#225;ticas.<span class="ao_explain"> Si no desea agregar Ads en p&#225;ginas especiales use esto &lt;!--noads--&gt; tag !<br>Marcando esta casilla omitir&#225; Ads para<b>todas</b> las p&#225;ginas est&#225;ticas</span>';

$checkPolicyProtect = '> Ocultar los anuncios de banner en las p&#225;ginas que puedan vulnerar la pol&#237;tica de Google.<span class="ao_explain"> <a href="https://support.google.com/adsense/bin/answer.py?hl=es&stc=aspe-1pp-it&answer=48182" target = "_blank">Para m&aacute;s informaci&#243;n leer las normas.</a></span>';
$nellePagineMostranoMoltiArticoli = 'En p&#225;ginas que muestran m&#225;s de un post (archivos, normal Homepage etc.)';
$nonMostrareAdSuQuestePag = 'No mostrar Ads en estas p&#225;ginas';
$supportaIlPlugin = 'Soporte de plugins';
$dono = 'Regalo un par de clics para el desarrollo de este gran plugin. Mis ingresos son pr&#225;cticamente igual y puedo utilizar todas las caracter&iacute;sticas.<span class="ao_explain"><br>Si usted est&#225; m&#225;s miser de T&iacute;o Gilito, anular su selecci&#243;n. </span>';
$puoInserireAnnunciUsandoWidget = 'Tambi&#233;n puede insertar Google Ads usando Widgets.';
$numeroDiLinks = 'N&uacute;mero de Links:';
$mostraSoloSeArticoloPiuLungoDi = 'Solo mostrar si el art&#237;culo es m&#225;s grande que:';
$caratteri = 'los caracteres.';
$caratteriDescr = '3000 caracteres = medio / alrededor de 5000 caracteres = Posts largo';
$postMultipli = 'M&uacute;ltiples Posts';
$intestazioniColonnePostMultipli = '<th>Ad N&deg;.</th><th>Tipo de Ad</th><th>Mostrar con</th><th>Alineaci&#243;n</th>';
$alto = '>Top';
$mezzo = '>Medio';
$basso = '>Inferior';
$caso = '>Random';
$centro = '>Centro';
$sinistra = '>Izquierda';
$destra = '>Derecha';
$nascondi = '>No mostrar';
$centraleSopraTitolo = '>Centro sobre el t&#237;tulo';
$sinistraSopraTitolo = '>Izquierda sobre el t&#237;tulo';
$destraSopraTitolo = '>Derecha sobre el t&#237;tulo';
$centraleSottoTitolo = '>Centro debajo del t&#237;tulo';
$sinistraSottoTitolo = '>Izquierda debajo del t&#237;tulo';
$destraSottoTitolo = '>Derecha debajo del t&#237;tulo';
$aggiornaLeOpzioni = 'Actualizar Opciones :)';
$titoloPrivacy = 'Pol&igrave;ticas del programa AdSense';
$spiegazioneBanPrivacy = 'No se puede publicar anuncios en p&#225;ginas con contenido violento, violaci&#243;n de derechos de autor, una invitaci&#243;n a los clics fraudulentos, etc.
Aquellos que violen las reglas, son expulsados del programa para siempre.';
$spiegazioneUtilizzoPrivacy = 'Los editores de AdSense deben regirse por una pol&#237;tica de privacidad que explique a los usuarios que es posible que determinados terceros introduzcan cookies en sus navegadores y las lean para recopilar informaci&#243;n como consecuencia de la publicaci&#243;n de anuncios en su sitio web.
<a target="_blank" href= "https://support.google.com/adsense/bin/answer.py?hl=es&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=48182#cook">
(Vea la secci&#243;n de Cookies)
</a>
<p>Para incluir la pol&#237;tica de privacidad en su sitio agregue &lt;!-- adsenseprivacypolicy --&gt; en p&agrave;gina donde desea que aparezca.</p>';
$informativaSullaPrivacy = 'informaci&#243;n en privacidad';
$dettagli = 'Detalles';
$sizes = array();
$sizes[] = array('desc' => '300 x 250 Rectangulo mediano', 'text' => '300x250');
$sizes[] = array('desc' => '336 x 280 Recatngulo grande', 'text' => '336x280');
$sizes[] = array('desc' => '728 x 90 Leaderboard', 'text' => '728x90');
$sizes[] = array('desc' => '160 x 600 Wide skyscraper', 'text' => '160x600');
$sizes[] = array('desc' => '320 x 50 Banner mobile', 'text' => '320x50');
$sizes[] = array('desc' => '234 x 60 Medio banner', 'text' => '234x60');
$sizes[] = array('desc' => '320 x 100 Grandes banner para dispositivos m&#243;viles', 'text' => '320x100');
$sizes[] = array('desc' => '468 x 60 Banner', 'text' => '468x60');
$sizes[] = array('desc' => '970 x 90 Leaderboard grande', 'text' => '970x90');
$sizes[] = array('desc' => '970 x 250 Billboard', 'text' => '970x250');
$sizes[] = array('desc' => '120 x 600 Skyscraper', 'text' => '120x600');
$sizes[] = array('desc' => '120 x 240 Banner vertical', 'text' => '120x240');
$sizes[] = array('desc' => '300 x 600 Skyscraper grande', 'text' => '300x600');
$sizes[] = array('desc' => '300 x 1050 Vertical', 'text' => '300x1050');
$sizes[] = array('desc' => '250 x 250 Square', 'text' => '250x250');
$sizes[] = array('desc' => '200 x 200 Cuadrado peque&ntilde;o', 'text' => '200x200');
$sizes[] = array('desc' => '180 x 150 Rectangulo peque&ntilde;o', 'text' => '180x150');
$sizes[] = array('desc' => '125 x 125 Boton', 'text' => '125x125');
$sizes[] = array('desc' => 'Dynamic Responsive', 'text' => 'dynamic');
$sizes[] = array('desc' => 'Responsive', 'text' => 'responsive');
?>
