<?php
$campoLingua = 'Lingua';
$campoLinguaDescr = 'Che lingua preferisci?';
$campoAdSenseIdDescr = 'Il Tuo Adsense ID (pub-....) <b>Inserire solo numeri</b>! (<a href="http://adsensexplosion.wordpress.com/2013/09/25/google-adsense-id-where-do-i-get-it/" target="_blank">Ulteriori Dettagli</a>)';
$campoAdSenseChannelDescr = '(Opzionale) <b>Inserire solo numeri</b> ! (<a href="http://www.google.com/adsense/support/bin/answer.py?answer=9868" target="_blank">Ulteriori Dettagli</a>)';
$campoProblema3Annuncio = 'Non compare 3&#176; banner Ads';
$campoProblema3AnnuncioDescr = 'In alcuni Temi (come ad esempio Mystique) Adsense Plugin Explosion non riesce a mostrare 3 banner. In questi casi, basta spuntare questa casella.  Se non hai problemi (nella maggior parte dei temi) lascialo deselezionato!';
$campoEscludiCSS = 'usa un CSS esterno';
$campoEscludiCSSDescr = 'cambia lo stile degli annunci, utilizzando gli stili CSS definiti in un foglio di stile piuttosto che stili interni. Se non hai problemi (nella maggior parte dei temi) lascialo deselezionato!';
$campoDisattivaSuMobile = 'disattiva su cellulari';
$campoDisattivaSuMobileDescr = 'plugin viene disabilitato, quando si utilizzano temi di telefonia mobile. Se non hai problemi (nella maggior parte dei temi) lascialo deselezionato!';
$campoAsync = 'usa annunci asincroni (Beta)';
$campoAsyncDescr = 'offre una migliore esperienza utente ai visitatori del tuo sito.';
$impostazioniGenerali = 'Impostazioni generali';
$cheTipoDiUtenteSei = 'Che Tipo di utente sei ?';
$utenteBase = '> <b>Utente Base</b>. Vuoi usare Google AdSense col minimo sforzo.';
$utenteEsperto = '> <b>Utente Esperto</b>. Desideri ottenere il massimo rendimento dai tuoi Google AdSense. Effettuerai una messa a punto.';
$configuraTuoiAnnunci = 'Configura i tuoi annunci';
$puoiImpostareFino8DiversiTipiDiAnnuncio = 'Puoi impostare fino ad 8 diversi tipi di annuncio.';
$TestoImmagini = '>Testo &amp; immagini';
$soloTesto = '>Solo testo';
$soloImmagini = '>Solo immagini';
$blocchiDiLink = '>Insieme di link';
$quadrati = '>Quadrati';
$arrotondati = '>Arrotondati';
$moltoArrotondati = '>Molto Arrotondati';
$soloSeDiversoDaImpostazioniGenerali = 'solo se diverso da<br>impostazioni generali';
$istruzioniDataAdSlot = 'ID dell\'annuncio. Lo trovi anche all\'interno del codice javascript dell\'annuncio. (solo numeri)';
$mostraAnnuncioNr = 'Mostra Ad Nr';
$quandoLaLarghezza = 'quando la larghezza <';
$nonUsare = '>Non usare';
$usaQuestaFunzioneSuTemiResponsive = 'Puoi usare questa funzionalit&agrave; (BETA) sui temi responsive';
$cliccaQuiPerVedereEsempiBanner = 'Clicca <a href="https://support.google.com/adsense/bin/answer.py?hl=it&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=185665" target="_blank">qui</a> per vedere gli esempi delle varie dimensioni.';
$angoli = 'Angoli: ';
$margineAttornoAnnuncio = 'Margine attorno annuncio:';
$doveMostrareGliAnnunci = 'Dove mostrare gli annunci';
$doveMostrareGliAnnunciDescr = 'Configura in quale parte dell\'area di contenuto devono apparire gli annunci. Per l\'inserimento in altre parti del blog puoi usare i Widget';
$postSingoliPagStatiche = 'Singoli post &amp; Pagine statiche';
$postSingoliPagStaticheDescr = 'Su singole Pagine (statiche o dinamiche) dove il contenuto &egrave; mostrato completamente (senza more).';
$checkAdsenseopt = '> Usalo solo negli articoli che contengono &lt;!--adsenseopt--&gt;: <span class="ao_explain"> Per usare il Plugin solo in specifici articoli spunta questa casella.<br>Se vuoi visualizzare i banner sulla maggior parte delle pagine, deselezionala !</span>';
$checkOmitPag = '> Non mostrare i banner sulle pagine statiche.<span class="ao_explain"> Se non vuoi visualizzare i banner su alcune pagine speciali, puoi usare il tag &lt;!--noads--&gt; <br>Spuntando questa casella, nasconderai i banner su <b>tutte</b> le pagine statiche !!!</span>';

$checkPolicyProtect = '> Nascondi i banner sulle pagine che potrebbero violare le Google Policy.<span class="ao_explain"> <a href="https://support.google.com/adsense/bin/answer.py?hl=it&stc=aspe-1pp-it&answer=48182" target = "_blank">Per maggiori informazioni leggi il regolamento.</a></span>';
$nellePagineMostranoMoltiArticoli = 'Nelle pagine che mostrano molti articoli. (archivi, Homepage normale, ecc)';
$nonMostrareAdSuQuestePag = 'Non mostrare gli annunci AdSense su queste pagine:';
$supportaIlPlugin = 'Supporto al plugin';
$dono = 'Dono qualche click per lo sviluppo di questo fantastico plugin. I miei guadagni rimangono praticamente invariati e posso utilizzare tutte le funzionalit&agrave;.<span class="ao_explain"><br>Se sei pi&ugrave; avaro di Paperon de Paperoni, deselezionala.</span>';
$puoInserireAnnunciUsandoWidget = 'Puoi anche inserire gli annunci Adsense usando il widget.';
$numeroDiLinks = 'Numero di Links:';
$mostraSoloSeArticoloPiuLungoDi = 'Mostra solo se l\'articolo &egrave; pi&ugrave; lungo di:';
$caratteri = 'caratteri.';
$caratteriDescr = '3000 caratteri = medio / intorno ai 5000 caratteri = lungo';
$postMultipli = 'Post Multipli';
$intestazioniColonnePostMultipli = '<th>Nr. Ad</th><th>Ad Type</th><th>Mostra Con il</th><th>Allineamento</th>';
$alto = '>Alto';
$mezzo = '>Mezzo';
$basso = '>Basso';
$caso = '>Caso';
$centro = '>Centro';
$sinistra = '>Sinistra';
$destra = '>Destra';
$nascondi = '>Nascondi';
$centraleSopraTitolo = '>centrale sopra il Titolo';
$sinistraSopraTitolo = '>a sinistra sopra il Titolo';
$destraSopraTitolo = '>a destra sopra il Titolo';
$centraleSottoTitolo = '>centrale sotto il titolo';
$sinistraSottoTitolo = '>a sinistra sotto il titolo';
$destraSottoTitolo = '>a destra sotto il titolo';
$aggiornaLeOpzioni = 'Aggiorna le opzioni';
$titoloPrivacy = 'Norme del programma AdSense';
$spiegazioneBanPrivacy = 'Non puoi pubblicare annunci su pagine aventi contenuto violento, violazione del copyright, invito a clicks fraudolenti, ecc.
I publisher AdSense che violano le norme, vengono espulsi dal programma per sempre.';
$spiegazioneUtilizzoPrivacy = 'I publisher AdSense devono redigere e rispettare norme sulla privacy che prevedono la possibilit&agrave; per le terze parti di inserire e leggere cookie sui browser degli utenti per raccogliere dati a seguito della pubblicazione di annunci sul sito web.
<a target="_blank" href= "https://support.google.com/adsense/bin/answer.py?hl=it&utm_medium=link&utm_campaign=ww-ww-et-asfe_&utm_source=aso&answer=48182#cook">
(Vedi regolamento paragrafo Cookie per la pubblicit&agrave; di Google)
</a>
<p>Per includere l\'Informativa sulla privacy sul tuo sito aggiungi &lt;!-- adsenseprivacypolicy --&gt; sulla pagina o sul post in cui desideri che appaia.</p>';
$informativaSullaPrivacy = 'Informativa sulla Privacy';
$dettagli = 'Dettagli';
$sizes = array();
$sizes[] = array('desc' => '300 x 250 Rettangolo medio', 'text' => '300x250');
$sizes[] = array('desc' => '336 x 280 Rettangolo grande', 'text' => '336x280');
$sizes[] = array('desc' => '728 x 90 Leaderboard', 'text' => '728x90');
$sizes[] = array('desc' => '160 x 600 Skyscraper largo', 'text' => '160x600');
$sizes[] = array('desc' => '320 x 50 Banner mobile', 'text' => '320x50');
$sizes[] = array('desc' => '234 x 60 Mezzo banner', 'text' => '234x60');
$sizes[] = array('desc' => '320 x 100 Banner grande per dispositivi mobili', 'text' => '320x100');
$sizes[] = array('desc' => '468 x 60 Banner', 'text' => '468x60');
$sizes[] = array('desc' => '970 x 90 Leaderboard grande', 'text' => '970x90');
$sizes[] = array('desc' => '970 x 250 Billboard', 'text' => '970x250');
$sizes[] = array('desc' => '120 x 600 Skyscraper', 'text' => '120x600');
$sizes[] = array('desc' => '120 x 240 Banner verticale', 'text' => '120x240');
$sizes[] = array('desc' => '300 x 600 Skyscraper grande', 'text' => '300x600');
$sizes[] = array('desc' => '300 x 1050 Verticale', 'text' => '300x1050');
$sizes[] = array('desc' => '250 x 250 Quadrato', 'text' => '250x250');
$sizes[] = array('desc' => '200 x 200 Quadrato piccolo', 'text' => '200x200');
$sizes[] = array('desc' => '180 x 150 Rettangolo piccolo', 'text' => '180x150');
$sizes[] = array('desc' => '125 x 125 Pulsante', 'text' => '125x125');
$sizes[] = array('desc' => 'Dynamic Responsive', 'text' => 'dynamic');
$sizes[] = array('desc' => 'Responsive', 'text' => 'responsive');
?>